config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #get 'welcome/index'
  resources :todos do
    resources :items do
      member do
        patch :complete
      end
    end
  end
  root "todos#index"
  #root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :todo

  def completed?
    !completed_at.blank?
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_todo
  before_action :set_item, except: [:create]
  
  def create
    @item = @todo.items.create(item_params)
    redirect_to @todo
  end

  def destroy
    @item = @todo.items.find(params[:id])
    if @item.destroy
      flash[:success] = "The item for this Todo was deleted."
    else
      flash[:error] = "The item for this Todo could not be deleted."
    end
    redirect_to @todo 
  end

  def complete
    @item.update_attribute(:completed_at, Time.now)
    redirect_to @todo, notice: "Item completed"
  end
  
  private
    def set_todo
      @todo = Todo.find(params[:todo_id])
    end

    def set_item
      @item = @todo.items.find(params[:id])
    end
    
    def item_params
      params[:item].permit(:content)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for([@todo, @todo.items.build]) do |f| %>
 <%= f.text_field :content, placeholder: "New Item" %>
 <%= f.submit %>
<% end %>

app/views/items/_item.html.erb
<div class="row clearfix">
  <% if item.completed? %>
    <div class="complete">
      <%= link_to complete_todo_item_path(@todo, item.id), method: :patch do %>
        <i style="opacity: 0.4;" class="fa fa-check"></i>
      <% end %>
    </div>
    <div class="item">
      <p style="opacity: 0.4;"><s><%= item.content %></s></p>
    </div>
    <div class="trash">
      <%= link_to todo_item_path(@todo, item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i>
      <% end %>
    </div>
  <% else %>
    <div class="complete">
      <%= link_to complete_todo_item_path(@todo, item.id), method: :patch do %>
        <i class="fa fa-clock-o" aria-hidden="true"></i>
      <% end %>       
    </div>
    <div class="item">
      <p><%= item.content %></p>
    </div>
    <div class="trash">
      <%= link_to todo_item_path(@todo, item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Jomolhari&display=swap" rel="stylesheet"> 
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1 class="todo_title">Editing Todo</h1>
<div class="forms">
  <%= render 'form', todo: @todo %>
</div>
<div class="links">
  <%= link_to 'Cancel', todos_path %>
</div>

app/views/todos/index.html.erb
<% @todos.each do |todo| %>
  <div class="index_row_clearfix">
    <h2 class="todo_title"><%= link_to todo.title, todo %></h2>
    <p class="todo_sub_title"><%= todo.description %></p>
  </div>
<% end %>
<div class="links">
  <%= link_to 'New Todo', new_todo_path %></td>
</div>
<!--- COMMENTED-OUT CODE 
<% if false %>
<p id="notice"><%= notice %></p>

<h1>Todos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.title %></td>
        <td><%= todo.description %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %> 
<% end %>
-- END OF COMMENTED-OUT CODE -->

app/views/todos/new.html.erb
<h1 class="todo_title">New Todo</h1>
<div class="forms">
  <%= render 'form', todo: @todo %>
</div>

<div class="links">
  <%= link_to 'Back', todos_path %>
</div>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<h2 class="todo_title"><%= @todo.title %></h2>
<p class="todo_sub_title"><%= @todo.description %></p>

<!-- COMMENTED OUT ---
<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo.description %>
</p>
--- End of comment -->
<div id="items_wrapper">
  <%= render @todo.items %>
  <div id="form">
    <%= render "items/form" %>
  </div>
</div>

<div class="links">
  <%= link_to 'Edit', edit_todo_path(@todo) %> |
  <%= link_to 'Delete', todo_path(@todo), method: :delete, data: { confirm: "Are you sure?" } %> |
  <%= link_to 'Back', todos_path %>
</div>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>